sudo: required

services:
- docker
#- redis-server
#- postgresql

#addons:
#  postgresql: "9.4"
#  apt:
#    packages:
#    - postgresql-9.4-postgis-scripts
#    - postgresql-9.4-postgis-2.2

script:
- True

after_success:
- ./scripts/travis_build.sh
#- ./scripts/travis_publish.sh

notifications:
  email: false
