version: '2'

services:
  postgresql:
    container_name: 'postgresql'
    build: ../../images/pgsql

  redis:
    container_name: 'redis'
    image: 'docker.io/redis:3.2'

  wait:
    image: waisbrot/wait
    links:
      - postgresql
      - redis
    environment:
      - TARGETS=postgresql:5432;redis:6379
