version: '2'

services:
  postgresql:
    container_name: 'test_postgresql'
    build: ../../images/pgsql

  redis:
    container_name: 'test_redis'
    image: redis

  wait:
    image: waisbrot/wait
    links:
      - postgresql
      - redis
    environment:
      - TARGETS=postgresql:5432;redis:6379
